### ISSUE TITLE
[docs] Comprehensive/Unified Documentation Website

### ISSUE THREAD

**Issue by nemesifier** [openwisp/openwisp-docs#107]
We need a comprehensive documentation which describes all the modules.

I want to avoid having the documentation of each module contained in this repo because that would make it harder to maintain: if we keep the documentation of each module in the module itself, we will be able to always request contributors to document their work because it will be easy for them.

We could use a system of git submodules, each OpenWISP module will be a submodule in this repo and we'll have some scripts which will glue everything together and generate the sphinx documentation.

The documentation could be divided as follows:

- user documentation (quickstart, guides, explanation of features)
- developer (information for developers and contributors)
- general (project goals, values, press, etc)

The user and developer sections will then have one sub-directory for each module, or something similar.

Each module could have a structure like the following:

```
# user:
/openwisp-controller/docs/user
/openwisp-controller/docs/user/feature1
/openwisp-controller/docs/user/feature2
# docs:
/openwisp-controller/docs/developer
/openwisp-controller/docs/developer/setup
/openwisp-controller/docs/developer/extending
```

The `Makefile` will take each module `user` and `developer` directory and copy the files as follows:

```
cp /openwisp-controller/docs/user/* /openwisp2-docs/user/openwisp-controller/
cp /openwisp-controller/docs/developer/* /openwisp2-docs/developer/openwisp-controller/
```

**Comment by pandafy** [comment]
We would also need to handle the versioning of the docs. E.g. OpenWISP v22 should show documentations from V1.0 of openwisp modules and v23 should show documentation from v1.1

It should be possible to map documentation OpenWISP version to modules version.

**Comment by nemesifier** [comment]
We are actively working on this task, anybody interested in collaborating, reviewing the docs, giving us feedback, please get in touch in the developer chat on matrix/gitter: https://matrix.to/#/#openwisp_development:gitter.im
