### ISSUE TITLE
[user] Document which objects can be shared among multiple organizations

### ISSUE THREAD

**Issue by nemesifier** [openwisp/openwisp-docs#55]
Some objects can be shared among multiple organizations, like Templates and VPN servers, they just need to have the `organization` set to nothing, but this is not explained anywhere.

**Comment by unnati914** [comment]
could i still work on this?

**Comment by nemesisdesign** [comment]
@unnati914 sure, please coordinate with us on https://gitter.im/openwisp/general so we can help you out if needed.

**Comment by unnati914** [comment]
sure! Thank you!

**Comment by atb00ker** [comment]
@unnati914 I don't think that's going to be the easiest issue to take if you don't have some knowledge about OpenWISP,
I could give you a hint though, after openwisp is setup and working on your machine, go to the `add` pages of all the models and in the `organization` dropdown, some of the models have `shared (no organization)` as an option.
These objects are the shared ones and we need to document what all can be shared between orgs! :smile:

**Comment by unnati914** [comment]
cool got it. thank you!

**Comment by nemesifier** [comment]
https://openwisp.io/docs/dev/users/user/basic-concepts.html#shared-objects
